---
- name: Install dependencies {{ ansible_os_family }}
  apt:
    name: '{{ item }}'
    state: installed
    update_cache: yes
  become: true
  with_items:
    - g++
    - imagemagick
    - libpq-dev
