---
- name: Add nodejs ppa {{ ansible_os_family }}
  raw: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  become: true

- name: Install nodejs {{ ansible_os_family }}
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true
